### ISSUE TITLE
Translate the text for the book cover

### ISSUE THREAD

**Issue by csev** [csev-es/py4e#54]
To put the book up on Amazon, we need to translate the cover text in this file:

https://github.com/csev-es/py4e/blob/master/book3/cover/backtext_es.docx

https://github.com/csev-es/py4e/blob/master/book3/cover/python_amazon_flat_04_final.pdf

Once I have the translated text I can talk to the graphic artist, and get a Spanish book cover made for review.

**Comment by don-charlie-pc** [comment]
Translated, check the last pull request. I just translated the docx file, I guess the pdf gets generated automatically.

**Comment by don-charlie-pc** [comment]
Fixed in a commit in the following PR https://github.com/csev-es/py4e/pull/58
