### ISSUE TITLE
Update the preface / title page

### ISSUE THREAD

**Issue by csev** [csev-es/py4e#55]
We need to add information regarding the translation to this page:

https://github.com/csev-es/py4e/blob/master/book3/A0-preface.mkd

We need a new line acknowledging the translators under.  Lets include all five contributors form the appendix in the list of translators.

https://github.com/csev-es/py4e/blob/master/book3/A0-preface.mkd#cr%C3%A9ditos

Also the date of the completion of the translation (it is now complete enough)

https://github.com/csev-es/py4e/blob/master/book3/A0-preface.mkd#historial-de-impresi%C3%B3n

**Comment by don-charlie-pc** [comment]
Fixed in a commit in the following PR https://github.com/csev-es/py4e/pull/58
